### ISSUE TITLE
zPIV not received by Android wallet

### ISSUE THREAD

**Issue by mfridge** [PIVX-Project/PIVX-Android#4]
Hi,

I transferred some zPIV to an address of my Android wallet (version 2.0.1) on November, 5th, but they are not shown in the Android wallet. The transaction has several thousand confirmations on presstab's block explorer and in my main wallet. To my understanding, any PIVX address should receive zPIV just like any "normal" PIV transaction.

I double-checked the address several times; it is correct. As I did not spend any further PIV to the Android wallet, the corresponding address is still showing up in the "receive coins" screen.

Is there anything I can assist with to further evaluate this issue?

Best regards,
Michael

**Comment by mfridge** [comment]
It seems as if I am alone with this issue. So I tried to get the private key, import into my PC wallet and let the Android wallet behind.

Through the wallet upgrade with version 2.0.1 (was is the version with the upgrade to BIP 44?), I have to mnemonic seeds - one "old" BIP 32 one and a "new" BIP 44 one. I used them both with the Coinomi recovery tool (https://coinomi.com/recovery-phrase-tool.html) and surprisingly none of the addresses generated by the Coinomi tool equals the ones that have been generated by the Android wallet.

Any ideas what I did wrong? Or is the Android wallet maybe using another BIP32 derivation path than the Coinomi tool is using for PIVX?

Any help is highly appreciated.

Kind regards,
Michael

**Comment by Klexx** [comment]
Hello,

>Any ideas what I did wrong? Or is the Android wallet maybe using another BIP32 derivation path than the Coinomi tool is using for PIVX?

please try BIP32 derivation path `m/44H/119H/0H/0`
 
kind regards

**Comment by mfridge** [comment]
Hi, that's the PIVX default in the tool. So it seems as if I can't get my private keys...

However, by PIVX support (great guys there!) I learned meanwhile that receiving zPIV is not yet possible in the Android wallet. This feature should be added somewhen, but nobody could tell me when. So I think it would be helpful to add this hint into the wallet to prevent other people from not getting access to their transferred zPIV.

Best regards and keep it purple!
Michael

**Comment by Klexx** [comment]
Hi,

> Hi, that's the PIVX default in the tool. So it seems as if I can't get my private keys...

OK. This path worked for me. Is it the same path in Settings->Export account ?

kind regards

**Comment by mfridge** [comment]
Hi Klexx,

sorry for the late reply. In Settings -> Export Account I have the BIP32 path "M/0H". When I choose this one, even the BIP32 public key differs from the one that is shown in the Android wallet. Honestly, I have no clue what is going on with my Android wallet...

Best regards,
Michael

**Comment by furszy** [comment]
Hey, sorry for the late reply.

Zc-spend transaction parsing issue is fixed now.
For faster support you can go to the PIVX Discord.

The next release contains this fix among other new features.

Going to let this issue open for some days and close it.
