### ISSUE TITLE
zPIV2 Transactions not being received

### ISSUE THREAD

**Issue by mongkeboy** [PIVX-Project/PIVX-Android#9]
Unable to receive zPIV2 transactions in mobile wallet.
Steps to reproduce:
1. Mint zPIV2
2. Spend to mobile wallet address: DNbA9iGz5ewqwKxbvzZQE3GUvygVMXGBTy
3. Check transaction is valid in block explorer: 8a3ad9213c1fe8966b4b910a69ed3cff7aec59b94634dc4596994117f53b41e1

Tried:
Reset Blockchain on mobile wallet.

**Comment by furszy** [comment]
Ok, thanks. Checking it

**Comment by furszy** [comment]
Sorry for the delay, issue solved. Will be released in the next update.

**Comment by mongkeboy** [comment]
Thank you!!!
